; NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
; RUN: llc -mtriple aarch64 -O0 -stop-after=instruction-select -global-isel -verify-machineinstrs %s -o - 2>&1 | FileCheck %s

%dag = type { { { i8, { i8 } }, { { i8, { i8 } }, { i8 } } }, { { i8, { i8 } }, { i8 } } }

define void @test_const(ptr %dst) {
  ; CHECK-LABEL: name: test_const
  ; CHECK: bb.1.entry:
  ; CHECK-NEXT:   liveins: $x0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:gpr64sp(p0) = COPY $x0
  ; CHECK-NEXT:   [[C:%[0-9]+]]:gpr32(i8) = G_CONSTANT i8 10
  ; CHECK-NEXT:   G_STORE [[C]](i8), [[COPY]](p0) :: (store (i8) into %ir.dst)
  ; CHECK-NEXT:   [[C1:%[0-9]+]]:gpr(i64) = G_CONSTANT i64 1
  ; CHECK-NEXT:   [[PTR_ADD:%[0-9]+]]:gpr(p0) = nuw inbounds G_PTR_ADD [[COPY]], [[C1]](i64)
  ; CHECK-NEXT:   [[C2:%[0-9]+]]:gpr32(i8) = G_CONSTANT i8 20
  ; CHECK-NEXT:   G_STORE [[C2]](i8), [[PTR_ADD]](p0) :: (store (i8) into %ir.dst + 1)
  ; CHECK-NEXT:   [[C3:%[0-9]+]]:gpr(i64) = G_CONSTANT i64 2
  ; CHECK-NEXT:   [[PTR_ADD1:%[0-9]+]]:gpr(p0) = nuw inbounds G_PTR_ADD [[COPY]], [[C3]](i64)
  ; CHECK-NEXT:   G_STORE [[C]](i8), [[PTR_ADD1]](p0) :: (store (i8) into %ir.dst + 2)
  ; CHECK-NEXT:   [[C4:%[0-9]+]]:gpr(i64) = G_CONSTANT i64 3
  ; CHECK-NEXT:   [[PTR_ADD2:%[0-9]+]]:gpr(p0) = nuw inbounds G_PTR_ADD [[COPY]], [[C4]](i64)
  ; CHECK-NEXT:   G_STORE [[C2]](i8), [[PTR_ADD2]](p0) :: (store (i8) into %ir.dst + 3)
  ; CHECK-NEXT:   [[C5:%[0-9]+]]:gpr(i64) = G_CONSTANT i64 4
  ; CHECK-NEXT:   [[PTR_ADD3:%[0-9]+]]:gpr(p0) = nuw inbounds G_PTR_ADD [[COPY]], [[C5]](i64)
  ; CHECK-NEXT:   [[C6:%[0-9]+]]:gpr32(i8) = G_CONSTANT i8 50
  ; CHECK-NEXT:   STRBBui [[C6]](i8), [[COPY]](p0), 4 :: (store (i8) into %ir.dst + 4)
  ; CHECK-NEXT:   STRBBui [[C]](i8), [[COPY]](p0), 5 :: (store (i8) into %ir.dst + 5)
  ; CHECK-NEXT:   STRBBui [[C2]](i8), [[COPY]](p0), 6 :: (store (i8) into %ir.dst + 6)
  ; CHECK-NEXT:   STRBBui [[C2]](i8), [[COPY]](p0), 7 :: (store (i8) into %ir.dst + 7)
  ; CHECK-NEXT:   STRBBui [[C]](i8), [[COPY]](p0), 0 :: (store (i8) into %ir.dst)
  ; CHECK-NEXT:   STRBBui [[C2]](i8), [[COPY]](p0), 1 :: (store (i8) into %ir.dst + 1)
  ; CHECK-NEXT:   STRBBui [[C]](i8), [[COPY]](p0), 2 :: (store (i8) into %ir.dst + 2)
  ; CHECK-NEXT:   STRBBui [[C2]](i8), [[COPY]](p0), 3 :: (store (i8) into %ir.dst + 3)
  ; CHECK-NEXT:   STRBBui [[C2]](i8), [[COPY]](p0), 4 :: (store (i8) into %ir.dst + 4)
  ; CHECK-NEXT:   STRBBui [[C]](i8), [[COPY]](p0), 5 :: (store (i8) into %ir.dst + 5)
  ; CHECK-NEXT:   STRBBui [[C2]](i8), [[COPY]](p0), 6 :: (store (i8) into %ir.dst + 6)
  ; CHECK-NEXT:   STRBBui [[C2]](i8), [[COPY]](p0), 7 :: (store (i8) into %ir.dst + 7)
  ; CHECK-NEXT:   RET_ReallyLR
entry:
 %updated = insertvalue
   ; Check that we're visiting constants with shared parts
   ; (deduplicated via LLVMContext, forming a proper DAG) correctly:
   %dag {
     { { i8, { i8 } }, { { i8, { i8 } }, { i8 } } } {
       { i8, { i8 } } {
         i8 10,
         { i8 } { i8 20 }
       },
       { { i8, { i8 } }, { i8 } } {
         { i8, { i8 } } {
           i8 10,
           { i8 } { i8 20 }
         },
         { i8 } { i8 20 }
       }
     },
     { { i8, { i8 } }, { i8 } } {
       { i8, { i8 } } {
         i8 10,
         { i8 } { i8 20 }
       },
       { i8 } { i8 20 }
     }
   },
   { { i8, { i8 } }, { i8 } } {
     { i8, { i8 } } {
       i8 10,
       { i8 } { i8 20 }
     },
     { i8 } { i8 50 }
   },
   0,
   1
 store %dag %updated, ptr %dst
 ; 10, 20, 10, 20, 50, 10, 20, 20 sequence is expected

 store
   ; Check that we didn't overwrite a previously seen constant
   ; while processing an insertvalue into it:
   %dag {
     { { i8, { i8 } }, { { i8, { i8 } }, { i8 } } } {
       { i8, { i8 } } {
         i8 10,
         { i8 } { i8 20 }
       },
       { { i8, { i8 } }, { i8 } } {
         { i8, { i8 } } {
           i8 10,
           { i8 } { i8 20 }
         },
         { i8 } { i8 20 }
       }
     },
     { { i8, { i8 } }, { i8 } } {
       { i8, { i8 } } {
         i8 10,
         { i8 } { i8 20 }
       },
       { i8 } { i8 20 }
     }
   },
   ptr %dst
 ; 10, 20, 10, 20, 20, 10, 20, 20 sequence is expected
 ret void
}
